version: '3'

services:
  build:
     context: .
     dockerfile: dockerfile
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

