version: '3'

services:
  nginx:
    build: .
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    image: httpd:latest
    ports:
      - 8080:80
    volumes:
      - ./app:/usr/local/apache2/htdocs/

networks:
  default:
    driver: bridge



